#!/bin/bash
#
# Copyright (c) Members of the EGEE Collaboration. 2007.
# See http://public.eu-egee.org/partners/ for details on
# the copyright holders.
# For license conditions see the license file or
# http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
#      Akos Frohner <Akos.Frohner@cern.ch>
#
# Poor man's adapter to work around ETICS newline and backslash handling problems.

basedir=$(cd $(dirname $0); echo $PWD)

USAGE="ant-configure [-Dproperty-name=property-value]..."

PROPS="$basedir/etics.properties"
rm -f $PROPS

for opt in "$@"; do
    case "$opt" in
        -D*=*)
            echo "$opt" | sed -e 's/^-D//' >>$PROPS
            ;;
         *)
            echo "Unknown option: '$opt'" >&2
            ;;
    esac
done

